### PR TITLE
Enable unified_mode for Chef 17

### PR DESCRIPTION
**Pull request by detjensrobert**
# Description

- Enables unified_mode for all resources
  - Bumps required Chef version to 15.3+
- Speeds up spec tests by caching the Chef run

## Issues Resolved

(none)

## Check List

- [x] All tests pass. See TESTING.md for details.
- [x] New functionality includes testing.
- [x] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Review by bmhughes — APPROVED** [review]

**Comment by ramereth** [comment]
@detjensrobert so it seems that centos-8 is failing currently when I test locally. The same error happens on the main branch. It might be nice to fix that in this PR if it's not a lot of work.

**Comment by detjensrobert** [comment]
@ramereth the failure in Dokken is due to the `ip_vs` kernel module not being loaded in the container. Testing that suite in a proper Openstack VM passes just fine.

**Comment by ramereth** [comment]
@detjensrobert oh right, I forgot about that! It works when I load that module locally.

**Review by ramereth — APPROVED** [review]

**Comment by kitchen-porter** [comment]
Released as: [6.0.0](https://github.com/sous-chefs/keepalived/releases/tag/6.0.0)

**Pull request merged**
