### PR TITLE
Add support for latest operating systems

### PR DESCRIPTION
**Pull request by Xorima**
# Description

Adds support for Centos-8, Ubuntu-20.04

## Issues Resolved

List any existing issues this PR resolves

## Check List

- [ ] All tests pass. See TESTING.md for details.
- [ ] New functionality includes testing.
- [ ] New functionality has been documented in the README if applicable.

### CODE REVIEW

**Comment by Xorima** [comment]
Errors are due to ip_vs module not being able to be loaded, see: https://github.com/chef/bento/issues/1279

**Comment by ramereth** [comment]
@Xorima so it seems both centos-8 and ubuntu-20.04 are using keepalived 2.x instead of 1.x. They are both failing because the ``ip_vs`` module is not loaded on the system. I'm not sure how best we can work around that given our current workflow. Any ideas?

Here's what you see from keepalived:
```
Apr 15 21:31:39 dokken Keepalived_healthcheckers[702]: IPVS: Can't initialize ipvs: Protocol not available
```

**Comment by Xorima** [comment]
I would get an issue raised with wherever those images are being created, and see if we can force a 1. install for now just to get the tests working?

**Comment by ramereth** [comment]
> I would get an issue raised with wherever those images are being created, and see if we can force a 1. install for now just to get the tests working?

It looks like these are created here: https://github.com/actions/virtual-environments/tree/master/images/linux

**Comment by Xorima** [comment]
Because we are in dokken I am unsure if this correlates correctly. 

I do wish I had access to run dokken on my laptop without it crashing :(

**Comment by ramereth** [comment]
@Xorima it should since the container will be using whatever the host has for modules/kernel.

**Comment by ramereth** [comment]
@Xorima would you like me to try and test this locally by making my own image based on their templates? I can at least try and replicate the problem and see what the proper fix might be

**Comment by Xorima** [comment]
Yes please, I am running low on time currently

**Pull request merged**
